# Generated by Django 4.1.5 on 2023-04-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliexpress_goods',
            name='model',
            field=models.TextField(null=True, verbose_name='商品编码'),
        ),
    ]
