# Generated by Django 4.1.6 on 2023-04-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Google_search_picture',
        ),
    ]
