apiVersion: cd.coding.net/v1alpha1
kind: GitSource
metadata:
  name: team-config
spec:
  git:
    url: https://e.coding.net/fubu/fubuguanwang/fob_website.git
    cred: git
    ref:
      branch: master
  templateRenderer:
    engine: Orbit
    path: /app01
    files:
    - values.yaml
  interval: 1m
